name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Keep-Alive Function
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            https://enqgmnrcblvfseeainwf.supabase.co/functions/v1/keep-alive
